export const GET_TASK = 'GET_TASK'
export const SET_LOADING = 'SET_LOADING'
export const SET_SORT = 'SET_SORT'
export const SET_ADMIN = 'SET_ADMIN'
export const SET_MESSAGE = 'SET_MESSAGE'
export const SET_EDITED_TASK = 'SET_EDITED_TASK'